apiVersion: apps/v1
kind: Deployment
metadata:
  name: elevator-service-app
  labels:
    app: elevator-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elevator-service-app
  template:
    metadata:
      labels:
        app: elevator-service-app
    spec:
      containers:
        - name: elevator-service-app
          image: ptyagi13/elevator-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: elevator-service-svc
spec:
  ports:
    - targetPort: 8082
      port: 80
  selector:
    app: elevator-service-app